@extends('emails.layout')
@section('title')
	留言訊息
@endsection
@section('content')
	<div>類別：{{$category}}</div>
	<div>留言者：{{$name}}</div>
	<div>留言者信箱：{{$email}}</div>
	<div>留言時間：{{$created_at}}</div>
	<div>內容：{!!$content!!}</div>
@endsection
@section('btn_start')
	<a href="{{env('APP_URL','https://api.uanalyze.com.tw')}}admin/messages/{{$id}}" style="text-decoration: none;color: #FFF;">
@endsection
@section('btn_text')
	前往留言後台
@endsection
@section('btn_end')
	</a>
@endsection